spring:
  config:
    activate:
      on-profile: redis-local-window

  data:
    redis:
      host: 192.168.210.79
      port: 6379
      password: "redis0378"

---
spring:
  config:
    activate:
      on-profile: redis-beta-linux

  data:
    redis:
      host: localhost
      port: 6379
      password: "redis0378"

